# Generated by Django 3.1.7 on 2021-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210301_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnology',
            field=models.ManyToManyField(to='core.Tecnology'),
        ),
    ]
