# Generated by Django 3.1.7 on 2021-04-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210414_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='status',
            new_name='concluido',
        ),
    ]
