# Generated by Django 3.1.7 on 2021-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210414_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tecnology',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnology',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tecnology',
        ),
    ]
